version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    depends_on:
      - nginx
    env_file:
      - .env
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok/ngrok.yml:ro
    command: start --config /etc/ngrok/ngrok.yml --all
